spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sfeir
    password: school
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: cb51cce1b336d53d61b3
            clientSecret: 8756276a0f250b6c6c8b73a0339f85ac02d11de1