spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-56443628.okta.com/oauth2/aus1nztlwsqX4tYHg5d7
          audience: spring-security-school
server:
  port: 8444

logging:
    level:
      root: debug
